#!/usr/bin/env python3
"""
MiniGo AlphaZero — Hybrid Training Pipeline

Workflow:
  1. Export current model to ONNX:       python export_onnx.py
  2. Generate self-play data in C++:     ./selfplay --model model.onnx --games 200
  3. Train the model in Python:          python train.py --data selfplay_data/
  4. Export updated ONNX model and repeat

This script handles step 3: reading binary self-play data and training
the PyTorch model. Training is resumable — optimizer state, epoch, and
trained file history are saved in the checkpoint.
"""

import argparse
import glob
import os
import struct
import sys
import time
import random

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

sys.path.insert(0, os.path.dirname(__file__))
from model import AlphaZeroNet


def read_selfplay_data(path):
    """Read a binary self-play data file generated by C++ selfplay."""
    with open(path, "rb") as f:
        data = f.read()

    pos = 0
    num_records = struct.unpack_from("i", data, pos)[0]; pos += 4

    records = []
    for _ in range(num_records):
        state_size = struct.unpack_from("i", data, pos)[0]; pos += 4
        state = np.frombuffer(data, dtype=np.float32, count=state_size, offset=pos).copy()
        pos += state_size * 4

        policy_size = struct.unpack_from("i", data, pos)[0]; pos += 4
        policy = np.frombuffer(data, dtype=np.float32, count=policy_size, offset=pos).copy()
        pos += policy_size * 4

        value = struct.unpack_from("f", data, pos)[0]; pos += 4

        records.append((state, policy, value))

    return records


def load_all_data(data_dir, exclude_files=None):
    """Load all self-play data files from a directory (recursively).

    Returns (records, loaded_files) where loaded_files is the set of
    file paths that were loaded (for tracking in checkpoint).
    """
    exclude_files = exclude_files or set()

    # Search recursively for .bin files
    files = sorted(glob.glob(os.path.join(data_dir, "**", "*.bin"), recursive=True))
    if not files:
        print(f"No data files found in {data_dir}")
        return [], set()

    all_records = []
    loaded_files = set()
    for f in files:
        abs_f = os.path.abspath(f)
        if abs_f in exclude_files:
            continue
        records = read_selfplay_data(f)
        all_records.extend(records)
        loaded_files.add(abs_f)
        print(f"  Loaded {f}: {len(records)} records")

    print(f"Total: {len(all_records)} training samples from {len(loaded_files)} files"
          f" ({len(exclude_files)} files skipped)")
    return all_records, loaded_files


def train_epoch(model, data, batch_size, optimizer, device):
    """Train one epoch on shuffled data."""
    model.train()
    random.shuffle(data)

    total_loss = 0.0
    total_policy_loss = 0.0
    total_value_loss = 0.0
    num_batches = 0

    for i in range(0, len(data) - batch_size + 1, batch_size):
        batch = data[i : i + batch_size]
        states, policies, values = zip(*batch)

        state_t = torch.tensor(np.array(states), dtype=torch.float32).to(device)
        policy_t = torch.tensor(np.array(policies), dtype=torch.float32).to(device)
        value_t = torch.tensor(values, dtype=torch.float32).unsqueeze(1).to(device)

        # Reshape state: (batch, C*H*W) -> (batch, C, H, W)
        board_size = int(np.sqrt(state_t.shape[1] // 17))
        state_t = state_t.view(-1, 17, board_size, board_size)

        # Forward
        logits, pred_value = model(state_t)

        # Losses
        policy_loss = -torch.sum(
            policy_t * torch.log_softmax(logits, dim=1)
        ) / state_t.size(0)
        value_loss = nn.functional.mse_loss(pred_value, value_t)
        loss = policy_loss + value_loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_policy_loss += policy_loss.item()
        total_value_loss += value_loss.item()
        num_batches += 1

    if num_batches == 0:
        return 0, 0, 0

    return (total_loss / num_batches,
            total_policy_loss / num_batches,
            total_value_loss / num_batches)


def main():
    parser = argparse.ArgumentParser(description="Train model on C++ self-play data")
    parser.add_argument("--data", default="selfplay_data",
                        help="Directory containing .bin data files (searched recursively)")
    parser.add_argument("--checkpoint", default="checkpoints/best_model.pt",
                        help="Model checkpoint to load/save")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=2e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--board", type=int, default=9)
    parser.add_argument("--filters", type=int, default=64)
    parser.add_argument("--blocks", type=int, default=5)
    parser.add_argument("--buffer-size", type=int, default=200_000,
                        help="Max training samples to keep (most recent)")
    parser.add_argument("--output-onnx", default="model.onnx",
                        help="Output ONNX model path")
    args = parser.parse_args()

    # Device
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"Device: {device}")

    # Load model
    model = AlphaZeroNet(
        board_size=args.board,
        input_channels=17,
        num_filters=args.filters,
        num_res_blocks=args.blocks,
    ).to(device)

    # Optimizer
    optimizer = optim.Adam(model.parameters(), lr=args.lr,
                           weight_decay=args.weight_decay)

    # Resume from checkpoint if it exists
    trained_files = set()
    start_iteration = 0

    os.makedirs(os.path.dirname(args.checkpoint) or "checkpoints", exist_ok=True)
    if os.path.exists(args.checkpoint):
        ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
        if isinstance(ckpt, dict) and "model_state_dict" in ckpt:
            # Full checkpoint with optimizer state
            model.load_state_dict(ckpt["model_state_dict"])
            if "optimizer_state_dict" in ckpt:
                optimizer.load_state_dict(ckpt["optimizer_state_dict"])
            trained_files = set(ckpt.get("trained_files", []))
            start_iteration = ckpt.get("iteration", 0)
            print(f"Resumed from checkpoint: {args.checkpoint}")
            print(f"  Iteration: {start_iteration}")
            print(f"  Previously trained on {len(trained_files)} files")
        else:
            # Legacy checkpoint (state_dict only)
            model.load_state_dict(ckpt)
            print(f"Loaded legacy checkpoint: {args.checkpoint}")
    else:
        print("Starting from scratch")

    # Load training data (skip already-trained files for incremental training)
    print(f"\nLoading self-play data from {args.data}...")
    data, new_files = load_all_data(args.data, exclude_files=trained_files)
    if not data:
        print("No new data to train on.")
        return

    # Trim to buffer size (keep most recent)
    if len(data) > args.buffer_size:
        data = data[-args.buffer_size:]
        print(f"Trimmed to {len(data)} most recent samples")

    # Train
    print(f"\nTraining for {args.epochs} epochs, batch_size={args.batch_size}")
    print("-" * 50)

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        loss, pl, vl = train_epoch(model, data, args.batch_size, optimizer, device)
        dt = time.time() - t0
        print(f"  Epoch {epoch:3d}  loss={loss:.4f}  "
              f"policy={pl:.4f}  value={vl:.4f}  ({dt:.1f}s)")

    # Update trained files set
    all_trained_files = trained_files | new_files

    # Save full checkpoint (model + optimizer + metadata)
    checkpoint = {
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "iteration": start_iteration + 1,
        "trained_files": list(all_trained_files),
        "board_size": args.board,
        "num_filters": args.filters,
        "num_res_blocks": args.blocks,
    }
    torch.save(checkpoint, args.checkpoint)
    print(f"\nSaved checkpoint: {args.checkpoint}")
    print(f"  Total trained files: {len(all_trained_files)}")

    # Export ONNX model for C++
    print("\nExporting ONNX model for C++...")
    from export_onnx import export_to_onnx
    model_cpu = model.cpu()
    export_to_onnx(model_cpu, args.output_onnx, board_size=args.board)


if __name__ == "__main__":
    main()
